### ISSUE TITLE
Posts paginator error, fails on hugo server --buildDrafts

### ISSUE THREAD

**Issue by FN-FAL113** [hugo-sid/hugo-blog-awesome#165]
**Describe the bug**
Seems like there is an error with the paginator, I'm new to using this theme and first time I encountered this issue.

**Steps to reproduce**
1. create new posts with ```hugo new content``` command
2. open development server with build draft posts with ``` hugo server --buildDrafts```
3. throws an error
```
Error: error building site: render: failed to render pages: render of "page" failed: "C:\Users\orbet\Documents\GitHub\FNDev-Blogs\themes\hugo-blog-awesome\layouts\_default\baseof.html:3:8": execute of template failed: template: _default/single.html:3:8: executing "_default/single.html" at <partial "head.html" .>: error calling partial: "C:\Users\orbet\Documents\GitHub\FNDev-Blogs\themes\hugo-blog-awesome\layouts\partials\head.html:2:8": execute of template failed: template: partials/head.html:2:8: executing "partials/head.html" at <partial "meta/main.html" .>: error calling partial: "C:\Users\orbet\Documents\GitHub\FNDev-Blogs\themes\hugo-blog-awesome\layouts\partials\meta\main.html:2:3": execute of template failed: template: partials/meta/main.html:2:3: executing "partials/meta/main.html" at <partial "meta/post.html" .>: error calling partial: "C:\Users\orbet\Documents\GitHub\FNDev-Blogs\themes\hugo-blog-awesome\layouts\partials\meta\post.html:5:21": execute of template failed: template: partials/meta/post.html:5:21: executing "partials/meta/post.html" at <.Paginate>: error calling Paginate: pagination not supported for this page: kind: "page", path: "/posts/event-capture",
```

**Expected behavior**
Should properly serve with build drafts argument on dev server

**Screenshots**
The lines that causes the error inside ```themes\hugo-blog-awesome\layouts\partials\meta\post.html```:
![image](https://github.com/hugo-sid/hugo-blog-awesome/assets/88238718/68f73b00-7859-4489-948b-559e66c5a21d)

**Device information**
 - OS: Windows
 - Browser: Chrome/Edge
 - Version latest

**Comment by deining** [comment]
I Encountered this error too when previewing the example site. Quickly I realized that this error happens  with hugo version v0.123.6 only. With hugo 0.122.0, preview of the example site works fine.

**Comment by MichielVanDerWinden** [comment]
I had some time left this morning so I looked into the issue and found that since v0.123.0 Hugo no longer allows pages of kind "Page" to create a .Paginate or .Paginator.
For now I've fixed it in my `post.html` by adding the following:

```html
    {{ if ne .Page.Kind "page" }}
    {{ $paginator := .Paginate (where .Pages "Section" "posts") }}
    {{ if $paginator }}
    <link rel="first" href="{{ $paginator.First.URL }}" />
    <link rel="last" href="{{ $paginator.Last.URL }}" />
    {{ if $paginator.HasPrev }}
    <link rel="prev" href="{{ $paginator.Prev.URL }}" />
    {{end }}
    {{ if $paginator.HasNext }}
    <link rel="next" href="{{ $paginator.Next.URL }}" />
    {{end }}
    {{end }}
    {{end }}
```

The only addition is the inclusion of an if-statement to check what kind of page we're on and prevent creation of the paginator on any pages of kind "page". This makes it possible for your posts overview (e.g. /posts) to create a paginator and use that in the post.html instantiaton, resulting in the `<head>` containing the specific pagination `<link>` references:

![image](https://github.com/hugo-sid/hugo-blog-awesome/assets/7113514/ee7344c3-73c0-4702-bbf4-94b9b5696f7b)
